services:
  - type: web
    name: diabetes-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn diabetes_backend.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: RENDER_EXTERNAL_HOSTNAME
        fromService:
          type: web
          name: diabetes-backend


      


# i will add DATABASE_URL later
    
 

