services:
  - type: web
    name: diabetes-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn diabetes_backend.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      


# i will add DATABASE_URL later
    
 

