services:
  - type: web
    name: diabetes-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn diabetes_backend.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: diabetes-db
          property: connectionString
databases:
  - name: diabetes-db
    plan: free
 

