# Generated by Django 5.1.4 on 2025-05-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('video', models.URLField()),
                ('description', models.TextField()),
                ('suitable_for', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Supper', 'Supper')], max_length=20)),
                ('diabet_type', models.CharField(choices=[('Type 1', 'Type 1'), ('Type 2', 'Type 2'), ('Gestational', 'Gestational'), ('All', 'All')], max_length=20)),
                ('calories', models.IntegerField()),
                ('carbs', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='diabetesprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Any', 'Any')], max_length=10),
        ),
    ]
