# Generated by Django 5.1.4 on 2025-05-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recipe_alter_diabetesprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diabetesprofile',
            name='diabetes_type',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='diabet_type',
        ),
        migrations.AddField(
            model_name='diabetesprofile',
            name='diabet_type',
            field=models.CharField(choices=[('Type 1', 'Type 1'), ('Type 2', 'Type 2'), ('Gestational', 'Gestational'), ('All', 'All')], default='Type 1', max_length=20),
            preserve_default=False,
        ),
    ]
