# Generated by Django 5.2.1 on 2025-05-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_devicepreference_medicationanswer_religionpreference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationanswer',
            name='diabetes_type',
            field=models.CharField(choices=[('Type 1', 'Type 1'), ('Type 2', 'Type 2'), ('Gestational', 'Gestational'), ('All', 'All')], max_length=20),
        ),
    ]
